# Debian GNU/Linux 12 (bookworm) with Python 3.12.0.
FROM python:3.12.0-slim-bookworm

# Create a directory for the application.
RUN mkdir -p /llm_app

# Set working directory.
WORKDIR /llm_app

# Create folder for requirements.
RUN mkdir -p /llm_app/requirements

# Include requirements.txt and start scripts.
COPY ../requirements/requirements.worker.dev.txt /llm_app/requirements/requirements.worker.dev.txt

# Prevents Python from writing pyc files to disc (equivalent to python -B option).
ENV PYTHONDONTWRITEBYTECODE 1

# Prevents Python from buffering stdout and stderr (equivalent to python -u option).
ENV PYTHONUNBUFFERED 1

# Ignore warning message from pip when installing packages as root.
ENV PIP_ROOT_USER_ACTION=ignore

# Install main dependencies.
RUN apt-get update --yes && \
    apt-get install --yes \
    # Operational system dependencies.
    python3-dev \
    unzip \
    curl \
    wget \
    vim \
    vim-gtk3 && \
    # Cleaning up unused files.
    # This folder contains cached package lists used by apt-get, and once the packages are installed, 
    # these lists are no longer needed. Removing them helps to keep the image smaller and more efficient.
    rm -rf /var/lib/apt/lists/*

# Install python requirements.
RUN pip3 install --upgrade pip && \
    pip3 install torch==2.5.1+cpu torchaudio==2.5.1+cpu torchvision==0.20.1+cpu --index-url https://download.pytorch.org/whl/cpu && \
    pip3 install -r /llm_app/requirements/requirements.worker.dev.txt

# One line installation of zsh.
# https://github.com/deluan/zsh-in-docker
RUN sh -c "$(wget -O- https://github.com/deluan/zsh-in-docker/releases/download/v1.2.1/zsh-in-docker.sh)"

# ZSH is now the default shell.
SHELL ["/usr/bin/zsh", "-c"]