# Base image for all agrilearn ecosystem (Python 3.10.12)
FROM nvidia/cuda:12.2.0-runtime-ubuntu22.04

# It sets up a user with specific UID and GID to avoid permission issues when mounting volumes from the host system into the container.
# The user is created with the same UID and GID as the host user, which allows for seamless file sharing between the host and the container without permission conflicts
ARG USER_NAME=worker-user
ARG USER_PASSWORD=worker-user
ARG USER_UID=1000
ARG USER_GID=1000

# Create a directory for the application.
RUN mkdir -p /llm_app

# Set working directory.
WORKDIR /llm_app

# Create folder for requirements.
RUN mkdir -p /llm_app/requirements

# Include requirements.txt and start scripts.
COPY ../requirements/requirements.worker.dev.gpu.txt /llm_app/requirements/requirements.worker.dev.gpu.txt

# Prevents Python from writing pyc files to disc (equivalent to python -B option).
ENV PYTHONDONTWRITEBYTECODE 1

# Prevents Python from buffering stdout and stderr (equivalent to python -u option).
ENV PYTHONUNBUFFERED 1

# Ignore warning message from pip when installing packages as root.
ENV PIP_ROOT_USER_ACTION=ignore

# Really necessary? APT-GET without interactive dialog.
ENV DEBIAN_FRONTEND=noninteractive

# Install main dependencies.
RUN apt-get update && \
    apt-get install --yes \
    # Operational system dependencies.
    sudo \
    python3-dev \
    python3-pip \
    python3-dev \
    python3-opencv \
    libglib2.0-0 \
    libcairo2-dev \
    pkg-config \
    unzip \
    curl \
    wget \
    zstd \
    jq \
    vim \
    vim-gtk3 && \
    # Cleaning up unused files.
    # This folder contains cached package lists used by apt-get, and once the packages are installed,
    # these lists are no longer needed. Removing them helps to keep the image smaller and more efficient.
    rm -rf /var/lib/apt/lists/*

# Avoid some errors in python packages installation.
RUN pip3 install --upgrade \
    pip \
    setuptools \
    wheel

# Pytorch compatible with CUDA 11.0.
# See: https://pytorch.org/get-started/previous-versions/
RUN pip3 install -f https://download.pytorch.org/whl/cpu \
    torch==2.5.1 \
    torchvision==0.20.1

# Remaining python dependencies.
RUN pip3 install --upgrade -r /llm_app/requirements/requirements.worker-gpu.dev.txt

# Create the worker user with sudo privilegies
RUN groupadd --gid $USER_GID $USER_NAME && \
    useradd --uid $USER_UID --gid $USER_GID --create-home $USER_NAME && \
    echo "%sudo ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers && \
    adduser $USER_NAME sudo

# Enable prompt color in .bashrc
RUN sed -i 's/^#force_color_prompt=yes/force_color_prompt=yes/' /home/$USER_NAME/.bashrc && \
    # Give worker user permissions for root folder.
    chown -R $USER_NAME:$USER_NAME /llm_app

# Important tools are installed here (black, isort, pytest, uv, etc)
ENV PATH="/home/${USER_NAME}/.local/bin:$PATH"

# Switch to the worker user
USER $USER_NAME

# Install Ollama
RUN curl -fsSL https://ollama.com/install.sh | sh

# Install opencode
RUN curl -fsSL https://opencode.ai/install | bash
